"""empty message

Revision ID: 17cfbc3bf814
Revises: c44ea094dfc9
Create Date: 2023-12-10 10:39:53.121132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cfbc3bf814'
down_revision = 'c44ea094dfc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
