"""empty message

Revision ID: 433da14da7c1
Revises: 43fa93a38775
Create Date: 2023-12-09 19:21:19.879534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433da14da7c1'
down_revision = '43fa93a38775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fotoPerfilUrl', sa.String(length=255), nullable=True))
        batch_op.drop_column('foto_perfil_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('fotoPerfilUrl')

    # ### end Alembic commands ###
