"""empty message

Revision ID: 9aa742fe5912
Revises: d1a6c5292c49
Create Date: 2023-12-10 16:41:58.033364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa742fe5912'
down_revision = 'd1a6c5292c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.alter_column('promedio',
               existing_type=sa.INTEGER(),
               type_=sa.Double(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.alter_column('promedio',
               existing_type=sa.Double(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
