"""empty message

Revision ID: c44ea094dfc9
Revises: 433da14da7c1
Create Date: 2023-12-10 10:36:30.597743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44ea094dfc9'
down_revision = '433da14da7c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
